version: '3.9'

services:
    icbf-database-service:
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8010
        volumes:
            - ../:/usr/src/app/
        ports:
            - "8002:8010"
        env_file:
            - ../.env
        networks:
            - icbf
        depends_on:
            - icbf-postgres-db
        restart: on-failure
            
    icbf-postgres-db:
        build:
            context: ../config_db
            dockerfile: Dockerfile
        volumes:
            - ../db/postgres:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - icbf

networks:
    icbf:
        external: True

volumes:
    icbf-postgres:
        external: true